function fou()
% Code initial :
% 'vase.m' cree par LEGAT Vincent
%
% Code modifie par :
% LAMOTTE Pierre
% Noma: 65441500
% Groupe 1257
% PCUR 06
% 
% Piece d'echecs :
% Generation d'un fou

T = [0 0 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29];
S = [0 0 0 1 1 2 2 3 3 4];
a = sqrt(3);
Xc = [1 0 1/2 1 3/2 2 1] ;
Yc = [0 0 a/2 a a/2 0 0] ;
Xc = Xc - mean(Xc(1:6));
Yc = Yc - mean(Yc(1:6));
Zc = ones(size(Xc));
Wc = [1 0.5 1 0.5 1 0.5 1];
X = Xc' * [0 3 3 3 2.5 3 2 2.5 2 2.1 1.7 1.8 1 0.6 1.8 1.8 1 1.2 1.4 1.8 1.2 0.8 0.6 0 0.2 0.1 0 0 0];
Y = Yc' * [0 3 3 3 2.5 3 2 2.5 2 2.1 1.7 1.8 1 0.6 1.8 1.8 1 1.2 1.4 1.8 1.2 0.8 0.6 0 0.2 0.1 0 0 0];
Z = Zc' * [1 1 1 1.3 1.4 1.4 1.6 1.7 1.8 1.8 2 2.3 2.5 6 6.2 6.3 6.5 6.4 6.8 7.1 7.9 8.3 8.5 9 9.1 9.2 9.2 9.2 9.2];
W = Wc' * [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1];
p = 2;

nt = length(T) - 1;
t = [T(p+1):0.05:T(nt-p+1)];
for i=0:nt-p-1
  Bt(i+1,:) = b(t,T,i,p);
end

ns = length(S) - 1;
s = [S(p+1):0.05:S(ns-p+1)];
for i=0:ns-p-1
  Bs(i+1,:) = b(s,S,i,p);
end

w = Bs' * W * Bt;
x = Bs' * (W .* X) * Bt ./ w;
y = Bs' * (W .* Y) * Bt ./ w;
z = Bs' * (W .* Z) * Bt ./ w;

createfigure(x,y,z); 
end

function createfigure(xdata1, ydata1, zdata1)
%CREATEFIGURE(XDATA1, YDATA1, ZDATA1)
%  XDATA1:  surface xdata
%  YDATA1:  surface ydata
%  ZDATA1:  surface zdata

%  Auto-generated by MATLAB on 20-Oct-2016 17:42:50

% Create figure
figure1 = figure('PaperType','<custom>','PaperSize',[20.98 29.68]);

% Create axes
axes1 = axes('Parent',figure1);
axis off
hold(axes1,'on');

% Create surf
surf(xdata1,ydata1,zdata1,'Parent',axes1,'FaceLighting','gouraud',...
    'LineStyle','none',...
    'FaceColor',[0 0 0]);

% Create light
light('Parent',axes1);

% Create light
light('Parent',axes1);

% Create light
light('Parent',axes1);

view(axes1,[120.6 26.4]);
grid(axes1,'on');

% Set the remaining axes properties
set(axes1,'DataAspectRatio',[1 1 1],'PlotBoxAspectRatio',[1 1 1.75]);
end

function u = b(t,T,j,p)
i = j+1;
if p==0
    u = (t>= T(i) & t < T(i+p+1)); return 
end

u = zeros(size(t));
if T(i) ~= T(i+p)
    u = u + ((t-T(i)) / (T(i+p) -T(i))) .* b(t,T,j,p-1);
end
if T(i+1) ~= T(i+p+1)
    u = u + ((T(i+p+1)-t) ./ (T(i+p+1) -T(i+1))) .* b(t,T,j+1,p-1);
end
end